---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: contracts-server
  labels:
    app: contracts-server
    tier: compute
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: contracts-server
        tier: compute
    spec:
      containers:
      - image: REGISTRY/kauri-contract-abis:TAG
        imagePullPolicy: Always
        name: web3-auth
        env:
          - name: API_PORT
            value: 8888
          - name: API_HOST
            value: 0.0.0.0
        ports:
        - containerPort: 8888
